# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [22]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [23]:
print(np.__version__)
np.show_config()


2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Abhinav/anaconda3/Library/include
    lib directory: C:/Users/Abhinav/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Abhinav/anaconda3/Library/include
    lib directory: C:/Users/Abhinav/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  cython:
    commands: cython
    linker: cython
    n

#### 3. Create a null vector of size 10

In [24]:
z = np.zeros(10)
print(z)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [25]:
a = np.zeros(10)
print(a.nbytes)


80


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [26]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [27]:
z = np.zeros(10)
z[4] = 1   
print(z)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [28]:
v = np.arange(10, 50)
print(v)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [29]:
v = np.arange(10, 50)  # example vector
reversed_v = v[::-1]
print(reversed_v)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [30]:
m = np.arange(9).reshape(3, 3)
print(m)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [31]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [32]:
I2 = np.identity(3)
print(I2)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [33]:
arr = np.random.random((3, 3, 3))
print(arr)


[[[0.89723749 0.94307884 0.12883495]
  [0.67512774 0.80430003 0.77275683]
  [0.04330039 0.27910548 0.76396892]]

 [[0.97933372 0.24794552 0.1185353 ]
  [0.10104186 0.76315281 0.12618588]
  [0.63490696 0.54036435 0.59711563]]

 [[0.43671953 0.31476599 0.35569233]
  [0.38561214 0.90887599 0.82791506]
  [0.26515487 0.49172701 0.56120202]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [34]:
arr = np.random.random((10, 10))

min_val = arr.min()
max_val = arr.max()

print("Array:\n", arr)
print("Minimum value:", min_val)
print("Maximum value:", max_val)


Array:
 [[0.67077115 0.01948356 0.18312655 0.46232676 0.10846417 0.6927559
  0.88450133 0.276686   0.39717086 0.69817045]
 [0.21473628 0.78374069 0.16436191 0.30127855 0.38113889 0.94667555
  0.31370153 0.17751963 0.93898343 0.59210344]
 [0.50364697 0.87031382 0.10844771 0.60972889 0.1773489  0.68249017
  0.45752525 0.46938205 0.09145713 0.4851587 ]
 [0.73270524 0.29368497 0.65441397 0.93421093 0.00475563 0.92140552
  0.27867944 0.12308798 0.59148244 0.3401536 ]
 [0.09426732 0.63227083 0.07548426 0.23968107 0.63694581 0.41342206
  0.96930089 0.29007966 0.28463598 0.14366143]
 [0.49321891 0.84393084 0.19318313 0.73000784 0.91786588 0.99489507
  0.70266737 0.40103606 0.62409397 0.93564445]
 [0.39870515 0.00168288 0.11076126 0.97915119 0.69508786 0.88540685
  0.49430974 0.17245086 0.76118988 0.43045456]
 [0.62707936 0.61921598 0.34459469 0.40785378 0.61794941 0.35230988
  0.07453382 0.32329261 0.60551222 0.85711541]
 [0.08275802 0.97208367 0.80310125 0.96691196 0.08084602 0.42179065
  0.0

#### 14. Create a random vector of size 30 and find the mean value

In [35]:
v = np.random.random(30)

mean_val = v.mean()
print("Vector:\n", v)
print("Mean value:", mean_val)


Vector:
 [0.81121823 0.00970808 0.09702231 0.13396251 0.14958323 0.42126295
 0.88110018 0.5951503  0.93959843 0.15342544 0.09758163 0.28729172
 0.93353672 0.50622612 0.88314055 0.73144584 0.88074877 0.07259213
 0.55706891 0.22108924 0.56610333 0.82765662 0.53687424 0.75251602
 0.34061369 0.45209427 0.53258727 0.05807343 0.04525976 0.53405512]
Mean value: 0.4669529024242844


#### 15. Create a 2d array with 1 on the border and 0 inside

In [36]:
arr = np.ones((5, 5))

arr[1:-1, 1:-1] = 0

print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [37]:
arr = np.array([[1, 2],
                [3, 4]])

bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(bordered_arr)


[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [38]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [39]:
vals = np.array([1, 2, 3, 4])

m = np.diag(vals, k=-1)

print(m)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [40]:
checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1  
checkerboard[::2, 1::2] = 1  

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [41]:
shape = (6, 7, 8)
flat_index = 99  
multi_index = np.unravel_index(flat_index, shape)
print(multi_index)


(np.int64(1), np.int64(5), np.int64(3))
